version: '3.1'
services:
  database:
    image: postgres
    container_name: library_database
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./scripts/app_library/01-create_db_app_library.sql:/docker-entrypoint-initdb.d/01.sql
      - ./scripts/app_library/02-insert_data_app_library.sql:/docker-entrypoint-initdb.d/02.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app_library
      - POSTGRES_USER=admin_ocp
      - POSTGRES_PASSWORD=Shangri_La
  web-service:
    image: oracle/glassfish
    container_name: library_web-service
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./datasource.properties:/datasource.properties
      - ./web-service/library-service/target/library.war:/glassfish5/glassfish/domains/domain1/autodeploy/library.war
    ports:
      - 4848:4848
      - 8081:8080
      - 8181:8181
    environment:
      - ADMIN_PASSWORD=Eldorado
  web-application:
    image: oracle/glassfish
    container_name: library_web-application
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./images:/images
      - ./library/library-webapp/target/Library.war:/glassfish5/glassfish/domains/domain1/autodeploy/Library.war
    ports:
      - 4949:4848
      - 80:8080
      - 8282:8181
    environment:
      - ADMIN_PASSWORD=Eldorado